language: node_js
node_js:
  - "8"

env:
  global:
    - SAUCE_USERNAME=pkozlowski
    - SAUCE_ACCESS_KEY=c5ea8b730bc9-378b-43e4-6e34-e66aa371
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/logs

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn

cache: yarn

before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh

script:
  - yarn ci && yarn api-doc:test
  - yarn global add codecov && codecov --disable=gcov -f coverage/lcov.info -F unit && codecov --disable=gcov -f coverage-e2e/lcov.info -F e2e
  - ./scripts/sauce_connect_block.sh
  - yarn saucelabs

after_script:
  - ./scripts/sauce_connect_teardown.sh

sudo: false
